In [7]:
import gym

from models import temporal_differencing_on_policy

In [8]:
# instantiate class

env = gym.make('FrozenLake-v1')

td = temporal_differencing_on_policy.TDOnPolicy(env=env,
                 num_episodes=100000, 
                 num_timesteps=1000,
                 epsilon=.95,
                 alpha=.8,
                 gamma=.85)

In [9]:
# run temporal differencing on-policy to update Q values:

Q = td.policy_computation()

In [10]:
# extract optimal policy from Q table:

df = td.find_optimal_policy(Q)

display(df)

    states  best_action
0        0            3
1        1            1
2        2            3
3        3            2
4        4            0
5        5            0
6        6            2
7        7            0
8        8            3
9        9            1
10      10            0
11      11            0
12      12            0
13      13            2
14      14            1
15      15            0